### 1️⃣ Прямой геокодинг — поиск города "Saint Petersburg"
GET https://api.openweathermap.org/geo/1.0/direct?q=Saint Petersburg&limit=5&appid=7c00b9c969b021b486ebf38462ae7e4c
Accept: application/json

### 2️⃣ Обратный геокодинг — по координатам Санкт-Петербурга
GET https://api.openweathermap.org/geo/1.0/reverse?lat=59.9343&lon=30.3351&limit=1&appid=7c00b9c969b021b486ebf38462ae7e4c
Accept: application/json

### 3️⃣ Текущая погода в Санкт-Петербурге
GET https://api.openweathermap.org/data/2.5/weather?lat=59.9343&lon=30.3351&units=metric&lang=en&appid=7c00b9c969b021b486ebf38462ae7e4c
Accept: application/json

### 4️⃣ Прогноз на 5 дней (каждые 3 часа) для Санкт-Петербурга
GET https://api.openweathermap.org/data/2.5/forecast?lat=59.9343&lon=30.3351&units=metric&lang=en&appid=7c00b9c969b021b486ebf38462ae7e4c
Accept: application/json

### 5️⃣ Загрязнение воздуха и UV индекс для Санкт-Петербурга
GET https://api.openweathermap.org/data/2.5/air_pollution?lat=59.9343&lon=30.3351&appid=7c00b9c969b021b486ebf38462ae7e4c
Accept: application/json
